import './js/refs';
import './js/modals/burger-menu';
import './js/cocktail-api';
import './js/main-gallery';
import './js/query-gallery';
import './js/modals/cocktail-modal';
import './js/select-gallery';
import './js/add-local-storage';
import './js/change-theme';
